### ISSUE TITLE
2.0.12: Failed to build SDL2 static on Windows with msvc

### ISSUE THREAD

**Issue by AlynxZhou** [mesonbuild/sdl2#19]
Got such error:

```
"link"  /MACHINE:x86 /OUT:flipclock.exe flipclock.exe.p/srcs_main.c.obj flipclock.exe.p/srcs_getarg.c.obj flipclock.exe.p/srcs_flipclock.c.obj "/nologo" "/release" "/nologo" "/DEBUG" "/PDB:flipclock.pdb" "subprojects\SDL2-2.0.12\libsdl2.a" "subprojects\SDL2-2.0.12\libsdl2main.a" "subprojects\SDL2_ttf-2.0.12\libsdl2_ttf.a" "subprojects\freetype-2.9.1\libfreetype.a" "winmm.lib" "version.lib" "imm32.lib" "setupapi.lib" "opengl32.lib" "/SUBSYSTEM:WINDOWS" "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "comdlg32.lib" "advapi32.lib"
MSVCRTD.lib(ftol2.obj) : error LNK2005: __ftol2_sse 已经在 libsdl2.a(src_stdlib_SDL_stdlib.c.obj) 中定义
  正在创建库 flipclock.lib 和对象 flipclock.exp
flipclock.exe : fatal error LNK1169: 找到一个或多个多重定义的符号
ninja: build stopped: subcommand failed.
```

(My system is Chinese and I don't know how to let msvc show English error message, but I can translate it by my self, I think the error is like "MSVCRTD.lib(ftol2.obj) : error LNK2005: __ftol2_sse is already defined in libsdl2.a(src_stdlib_SDL_stdlib.c.obj)" and "flipclock.exe : fatal error LNK1169: find one or more symbols that has multi-defination")

I build it with command `mkdir build`, `cd build`, `meson setup -Ddefault_library=static . ..` and `meson compile`. I am not sure why this happens.

**Comment by AlynxZhou** [comment]
My Project: https://github.com/AlynxZhou/flipclock/

**Comment by AlynxZhou** [comment]
After using `meson setup --default-library=static . ..`, `MSVCRTD.lib` becomes `LIBCMT.lib`, and the error still exists.

**Comment by jpakkane** [comment]
The wrap has only been tested on 64 bit Windows. Probably some configuration or feature detection goes wrong on 32 bit Visual Studio.

**Comment by AlynxZhou** [comment]
> The wrap has only been tested on 64 bit Windows. Probably some configuration or feature detection goes wrong on 32 bit Visual Studio.

I want to build a 32-bit one so it can run on both 32bit and 64bit Windows

**Comment by jpakkane** [comment]
Should be fixed by https://github.com/mesonbuild/sdl2/pull/21.

**Comment by AlynxZhou** [comment]
Currently I am using the prebuilt libraries provided by SDL.org with my own finding code, let me try this if I have time.

**Comment by AlynxZhou** [comment]
Tested with x86 MSVC and confirmed that it was fixed. Thanks!
